apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-backend
spec:
  selector:
    matchLabels:
      app: nestjs-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-backend
    spec:
      containers:
        - name: nestjs-backend
          image: gcr.io/nodejs-k8s-350419/dilanbrandix
          ports:
            - containerPort: 3000 
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"